[[language]]
name = "json"
grammar = { git = "https://github.com/tree-sitter/tree-sitter-json.git", rev = "73076754005a460947cafe8e03a8cf5fa4fa2938" }
extensions =  [ "json", "avsc", "geojson", "gltf", "har", "ice", "JSON-tmLanguage", "jsonl", "mcmeta", "tfstate", "tfstate.backup", "topojson", "webapp", "webmanifest" ]